spring:
  kafka:
    template:
      default-topic: new-investments
    producer:
      bootstrap-servers:
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://${BROKER}/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=";